CommandDescrptionJoin: "&4valami"
JoinmsgisSaved: "&2mentve"
CommandDescrptionLeave: "&5leave"
LevaemsgisSaved: "&6mentve"
NewJoinmsg: "&3join:&r"
NewLeavemsg: "&3Leave:&r"
DefaultLeave: "&8[&c-&8]&7"
DefaultLeave2: "&a Lelépett a szerverről :/"
DefaultJoin: "&8[&3+&8]&7"
DefaultJoin2: "&a Belépett a szerverre :)"
UptimeDescription: "&7uptime parancs"
RemovedUptime: "&7törölve"
NoPermission: "&9Nincs jogod!!!!"
PlayerIsNotPlayedBefore: "&5A Játékos nem játszott még a szerveren"
BadUsage: "&2rosz használat: /uptime <Player> \ /uptime del \ /uptime"
Sec: "&4Másodperc"
Minute: "&6perc"
Hour: "&8óra"